In [1]:
import pandas as pd
import numpy as np

In [2]:
s1=pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
                   index=["a", "c", "e", "f", "g"])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [6]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                       index=["Ohio", "Texas", "Colorado"])


In [7]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                       index=["Utah", "Ohio", "Texas", "Oregon"])

In [8]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [9]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [10]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [11]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})

In [12]:
df1

A
0  1
1  2

In [13]:
df2

B
0  3
1  4

In [14]:
df1+df2 #If you add DataFrame objects with no column or row labels in common, the result will contain all nulls

A   B
0 NaN NaN
1 NaN NaN

Arithmetic methods with fill values


In [15]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                       columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                       columns=list("abcde"))

In [16]:
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [17]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [18]:
df2.loc[1, "b"] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [19]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [20]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [21]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [22]:
df1.rdiv(1) #Each has a counterpart, starting with the letter r, that has arguments reversed.

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [23]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [24]:
arr[0]

array([0., 1., 2., 3.])

In [25]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [26]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                         columns=list("bde"),
                         index=["Utah", "Ohio", "Texas", "Oregon"])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [27]:
series=frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [28]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [29]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])
series2

b    0
e    1
f    2
dtype: int32

In [30]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [31]:
series3 = frame["d"]
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [32]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [34]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

Function Application and Mapping

In [35]:
frame = pd.DataFrame(np.random.standard_normal((4, 3)),
                         columns=list("bde"),
                         index=["Utah", "Ohio", "Texas", "Oregon"])

In [36]:
frame

b         d         e
Utah    1.649969 -0.241066 -1.440407
Ohio    0.535714  2.027346 -0.397013
Texas  -0.060054 -0.203357  0.988448
Oregon  0.319711 -0.810867  1.220229

In [37]:
np.abs(frame)

b         d         e
Utah    1.649969  0.241066  1.440407
Ohio    0.535714  2.027346  0.397013
Texas   0.060054  0.203357  0.988448
Oregon  0.319711  0.810867  1.220229

In [42]:
def f1(x):
    return x.max()-x.min()

frame.apply(f1,axis="rows") #row wise

b    1.710023
d    2.838213
e    2.660636
dtype: float64

In [41]:
frame.apply(f1,axis="columns") #column wise 

Utah      3.090376
Ohio      2.424359
Texas     1.191806
Oregon    2.031096
dtype: float64

In [43]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

frame.apply(f2)

b         d         e
min -0.060054 -0.810867 -1.440407
max  1.649969  2.027346  1.220229

Sorting and ranking 

In [44]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int32

In [45]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [46]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                         index=["three", "one"],
                         columns=["d", "a", "b", "c"])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [47]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [48]:
frame.sort_index(axis="columns")

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [49]:
frame.sort_index(axis="columns",ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [50]:
obj = pd.Series([4, 7, -3, 2])
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [51]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [52]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [53]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [54]:
obj.sort_values(na_position="first") #Missing values can be sorted to the start instead by using the na_position option

1    NaN
3    NaN
4   -3.0
5    2.0
0    4.0
2    7.0
dtype: float64

Axis Indexes with Duplicate Labels

In [56]:
obj = pd.Series(np.arange(5), index=["a", "a", "b", "b", "c"])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int32

In [57]:
obj.index.is_unique #The is_unique property of the index can tell you whether or not its labels are unique

False

In [58]:
obj["a"]

a    0
a    1
dtype: int32

In [59]:
df = pd.DataFrame(np.random.standard_normal((5, 3)),
                      index=["a", "a", "b", "b", "c"])

df

0         1         2
a -1.754410 -1.858233  0.698638
a -0.540587  0.110714 -0.716194
b  1.789169 -0.453456  0.863441
b -0.273695 -0.443530 -2.238271
c -0.523859 -1.752642  0.569892

In [60]:
df.loc["b"]

0         1         2
b  1.789169 -0.453456  0.863441
b -0.273695 -0.443530 -2.238271

In [61]:
df.loc["c"]

0   -0.523859
1   -1.752642
2    0.569892
Name: c, dtype: float64