In [2]:
import pandas as pd
import numpy as np

Database-Style DataFrame Joins

In [3]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                        "data1": pd.Series(range(7), dtype="Int64")})

In [4]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [5]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                        "data2": pd.Series(range(3), dtype="Int64")})

In [6]:
df2

key  data2
0   a      0
1   b      1
2   d      2

In [7]:
pd.merge(df1,df2) #This is an example of a many-to-one join; the data in df1 has multiple rows labeled a and b, whereas df2 has only one row for each value in the key column. 

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [8]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                        "data1": pd.Series(range(7), dtype="Int64")})

In [9]:
df3

lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [10]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                        "data2": pd.Series(range(3), dtype="Int64")})

In [11]:
df4

rkey  data2
0    a      0
1    b      1
2    d      2

In [12]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

You may notice that the "c" and "d" values and associated data are missing from the result. By default, pandas.merge does an "inner" join; the keys in the result are the intersection, or the common set found in both tables. Other possible options are "left", "right", and "outer". The outer join takes the union of the keys, combining the effect of applying both left and right joins:

In [13]:
pd.merge(df1, df2, how="outer")

key  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0
6   c      3   <NA>
7   d   <NA>      2

In [14]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In an outer join, rows from the left or right DataFrame objects that do not match on keys in the other DataFrame will appear with NA values in the other DataFrame's columns for the nonmatching rows.



In [15]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                        "data1": pd.Series(range(6), dtype="Int64")})

In [16]:
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                        "data2": pd.Series(range(5), dtype="Int64")})

In [17]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [18]:
df2

key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [19]:
pd.merge(df1, df2, on="key", how="left")

key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

In [20]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                         "key2": ["one", "two", "one"],
                         "lval": pd.Series([1, 2, 3], dtype='Int64')})

In [21]:
left

key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [22]:
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                          "key2": ["one", "one", "one", "two"],
                          "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})

In [23]:
right

key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [24]:
pd.merge(left,right,on=["key1","key2"],how="outer")

key1 key2  lval  rval
0  foo  one     1     4
1  foo  one     1     5
2  foo  two     2  <NA>
3  bar  one     3     6
4  bar  two  <NA>     7

In [25]:
pd.merge(left,right,on="key1")

key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

Merging on index 

In [26]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                          "value": pd.Series(range(6), dtype="Int64")})

In [27]:
left1

key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [28]:
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])

In [29]:
right1

group_val
a        3.5
b        7.0

In [30]:
pd.merge(left1,right1,left_on="key",right_index=True)

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [31]:
pd.merge(left1,right1,left_on="key",right_index=True,how="outer")

key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [32]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio",
                                   "Nevada", "Nevada"],
                          "key2": [2000, 2001, 2002, 2001, 2002],
                          "data": pd.Series(range(5), dtype="Int64")})

In [33]:
lefth

key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [36]:
righth_index=pd.MultiIndex.from_arrays(
    [
        ["Nevada","Nevada","Ohio","Ohio","Ohio","Ohio"],
        [2001,2000,2000,2000,2001,2002]
    ]
)

In [37]:
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [38]:
righth=pd.DataFrame({"event1":pd.Series([0,2,4,6,8,10],dtype="int64",index=righth_index),
                     "event2":pd.Series([1,3,5,7,9,11],dtype="int64",index=righth_index)})


In [39]:
righth

event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [40]:
pd.merge(lefth, righth, left_on=["key1", "key2"], right_index=True)

key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1

In [41]:
pd.merge(lefth, righth, left_on=["key1", "key2"],
             right_index=True, how="outer")

key1  key2  data  event1  event2
0    Ohio  2000     0     4.0     5.0
0    Ohio  2000     0     6.0     7.0
1    Ohio  2001     1     8.0     9.0
2    Ohio  2002     2    10.0    11.0
3  Nevada  2001     3     0.0     1.0
4  Nevada  2002     4     NaN     NaN
4  Nevada  2000  <NA>     2.0     3.0

In [42]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                         index=["a", "c", "e"],
                         columns=["Ohio", "Nevada"]).astype("Int64")

left2

Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [43]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                          index=["b", "c", "d", "e"],
                          columns=["Missouri", "Alabama"]).astype("Int64")

right2

Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [44]:
left2.join(right2, how="inner")

Ohio  Nevada  Missouri  Alabama
c     3       4         9       10
e     5       6        13       14

In [45]:
left2.join(right2, how="outer")

Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [47]:
left1.join(right2, on="key")

key  value  Missouri  Alabama
0   a      0      <NA>     <NA>
1   b      1         7        8
2   a      2      <NA>     <NA>
3   a      3      <NA>     <NA>
4   b      4         7        8
5   c      5         9       10

Concatenating along an axis 

In [48]:
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.concatenate([arr,arr],axis=1) #axis1 refers to the vertical columns 

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [50]:
s1=pd.Series([0,1],index=["a","b"],dtype="int64")
s2=pd.Series([2,3,4],index=["c","d","e"],dtype="int64")
s3=pd.Series([5,6],index=["f","g"],dtype="int64")

In [51]:
s1

a    0
b    1
dtype: int64

In [52]:
s2

c    2
d    3
e    4
dtype: int64

In [53]:
s3

f    5
g    6
dtype: int64

In [54]:
pd.concat([s1,s2,s3]) #done on the basis of rows

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [55]:
pd.concat([s1,s2,s3],axis=1) #done on the basis of columns 

0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [56]:
s4=pd.concat([s1,s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [57]:
pd.concat([s1,s4],axis="columns") #this is outer join

0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [58]:
pd.concat([s1, s4], axis="columns", join="inner")

0  1
a  0  0
b  1  1

In [59]:
result = pd.concat([s1, s1, s3], keys=["one", "two", "three"])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: int64

In [60]:
result.unstack()

a    b    f    g
one    0.0  1.0  NaN  NaN
two    0.0  1.0  NaN  NaN
three  NaN  NaN  5.0  6.0

Combining data with overlap

In [61]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
                  index=["f", "e", "d", "c", "b", "a"])
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [62]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
                  index=["a", "b", "c", "d", "e", "f"])
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

In [63]:
np.where(pd.isna(a), b, a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

Above, whenever values in a are null, values from b are selected, otherwise the non-null values from a are selected. Using numpy.where does not check whether the index labels are aligned or not 