In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[5:8]

array([5, 6, 7])

In [6]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [7]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [8]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [9]:
#With higher dimensional arrays, you have many more options. In a two-dimensional array, the elements at each index are no longer scalars but rather one-dimensional arrays
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [11]:
list=[1,2,3,4,5]
list[:4]

[1, 2, 3, 4]

In [13]:
list[1:]

[2, 3, 4, 5]