In [1]:
import numpy as np

In [3]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
arr*arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [5]:
arr-arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [7]:
arr**2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [8]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [9]:
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])